[environment]
extra-paths = [
    "src"
]
python-version = "3.12"

[rules]
byte-string-type-annotation="warn"
call-non-callable="warn"
conflicting-argument-forms="warn"
conflicting-declarations="warn"
conflicting-metaclass="warn"
cyclic-class-definition="warn"
cyclic-type-alias-definition="warn"
duplicate-base="warn"
duplicate-kw-only="warn"
escape-character-in-forward-annotation="warn"
fstring-type-annotation="warn"
implicit-concatenated-string-type-annotation="warn"
inconsistent-mro="warn"
index-out-of-bounds="warn"
instance-layout-conflict="warn"
invalid-argument-type="warn"
invalid-assignment="warn"
invalid-attribute-access="warn"
invalid-await="warn"
invalid-base="warn"
invalid-context-manager="warn"
invalid-declaration="warn"
invalid-exception-caught="warn"
invalid-explicit-override="warn"
invalid-generic-class="warn"
invalid-key="warn"
invalid-legacy-type-variable="warn"
invalid-metaclass="warn"
invalid-method-override="warn"
invalid-named-tuple="warn"
invalid-newtype="warn"
invalid-overload="warn"
invalid-parameter-default="warn"
invalid-paramspec="warn"
invalid-protocol="warn"
invalid-raise="warn"
invalid-return-type="warn"
invalid-super-argument="warn"
invalid-syntax-in-forward-annotation="warn"
invalid-type-alias-type="warn"
invalid-type-arguments="warn"
invalid-type-checking-constant="warn"
invalid-type-form="warn"
invalid-type-guard-call="warn"
invalid-type-guard-definition="warn"
invalid-type-variable-constraints="warn"
missing-argument="warn"
missing-typed-dict-key="warn"
no-matching-overload="warn"
non-subscriptable="warn"
not-iterable="warn"
override-of-final-method="warn"
parameter-already-assigned="warn"
positional-only-parameter-as-kwarg="warn"
raw-string-type-annotation="warn"
static-assert-error="warn"
subclass-of-final-class="warn"
super-call-in-named-tuple-method="warn"
too-many-positional-arguments="warn"
type-assertion-failure="warn"
unavailable-implicit-super-arguments="warn"
unknown-argument="warn"
unresolved-attribute="warn"
unresolved-import="warn"
unresolved-reference="warn"
unsupported-bool-conversion="warn"
unsupported-operator="warn"
zero-stepsize-in-slice="warn"
ambiguous-protocol-member="warn"
deprecated="warn"
ignore-comment-unknown-rule="warn"
invalid-ignore-comment="warn"
possibly-missing-attribute="warn"
possibly-missing-implicit-call="warn"
possibly-missing-import="warn"
redundant-cast="warn"
undefined-reveal="warn"
unresolved-global="warn"
unsupported-base="warn"
useless-overload-body="warn"
division-by-zero="warn"
possibly-unresolved-reference="warn"
unused-ignore-comment="warn"